//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Pet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_pet
    {
        public string Кличка_питомца { get; set; }
        public int Номер_комнаты_проживания { get; set; }
        public System.DateTime Дата_заезда { get; set; }
        public string Оказанная_услуга { get; set; }
        public string Сотрудник { get; set; }
    }
}
