//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Pet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public System.Guid ID_pet { get; set; }
        public System.Guid ID_care { get; set; }
        public System.DateTime Date_care { get; set; }
    
        public virtual Care Care { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
